### PR TITLE
fix can't join

### PR DESCRIPTION
**Pull request by encyptAES**
## Summary

fix a resource_packs_info_packet endcoding bug
## Checklist

- [X] If code changes were made then they have been tested.
- [X] This PR fixes an issue.

### CODE REVIEW

**Comment by MFDGaming** [comment]
It already works. What you did isn’t following the mcbe protocol.

**Comment by MFDGaming** [comment]
Or no my bad

**Comment by encyptAES** [comment]
haha

**Comment by HunterAzar** [comment]
:D

**Pull request merged**
