### PR TITLE
Adds "set_join_message()" and "get_join_message()" for plugins.

### PR DESCRIPTION
**Pull request by ElectroGamesDev**

### CODE REVIEW

**Comment by plun1331** [comment]
I feel like it would make more sense to make those methods a part of the server object, and have the join event access an attribute (such as `join_message`) on the server object.

**Comment by ElectroGamesDev** [comment]
Nah since in plugins, in the Join Event, players can use `event.set_join_message("Message")`, etc. This is more simple and I believe it makes more sense :)

**Comment by plun1331** [comment]
Your implementation also, just from looking at it, appears to not work.
When broadcasting the message in `handle_request_chunk_radius_packet` (which also doesn't make too much sense to me, shouldn't it be broadcasted while handling the login packet?), it creates a new instance of the event, and the message simply defaults to the original.
The methods are also redundant, you can simply access the `join_message` attribute of the event.
Additionally, how do you plan to get the existing instance of the event in the first place? (there is probably a simple way to do this that I am not aware of, I haven't taken a good look at the events system until now, it also appears to be incomplete?)

**Comment by ElectroGamesDev** [comment]
I have tested and it is working. It is also in `handle_request_chunk_radius_packet` because that is where MDFGaming called the Player Join Event. I also plan on getting the event using `event.` as MDFGamimg added that yesterday. Everything is working as I have tested with my plugin.

**Comment by plun1331** [comment]
I still don't like the redundant methods, but I guess MFD can decide

**Comment by ElectroGamesDev** [comment]
What do you mean "redundant methods"?

**Comment by plun1331** [comment]
> What do you mean "redundant methods"?

Instead of calling a method, you can just set the `join_message` attr on the event

**Comment by ElectroGamesDev** [comment]
This is easier for people who want to create plugins to set the join message or to get it.

**Comment by plun1331** [comment]
> This is easier for people who want to create plugins to set the join message or to get it.

fair enough

**Comment by MFDGaming** [comment]
Python does not need setters and getters, the only thing it does is hurt the performance, less Non needed code = better Performance

**Pull request closed without merging**
