### PR TITLE
Create start.cmd when doesn't exist

### PR DESCRIPTION
**Pull request by ElectroGamesDev**

### CODE REVIEW

**Comment by Zekiah-A** [comment]
Would this be the same for MacOS and Linux though?

**Comment by HunterAzar** [comment]
make for windows, macos, linux

**Comment by ElectroGamesDev** [comment]
> Would this be the same for MacOS and Linux though?
Not sure lol

**Comment by ElectroGamesDev** [comment]
> make for windows, macos, linux

Alright lol

**Comment by Zekiah-A** [comment]
> make for windows, macos, linux

Agreed, the macos and linux ones should be the same, since they both use the UNIX commands as far as i know, only windows is different

**Comment by Zekiah-A** [comment]
Sad life..

**Comment by ElectroGamesDev** [comment]
:(

**Pull request closed without merging**
