### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by TheVeryStarlk**

### CODE REVIEW

**Comment by nougator** [comment]
What's the difference?

**Comment by TheVeryStarlk** [comment]
> 
> 
> What's the difference?

Changed logo and rephrased* the whole readme

**Comment by nougator** [comment]
I don't see any differences

**Comment by TheVeryStarlk** [comment]
> 
> 
> I don't see any differences

Ah... There is actually, look carefully.

**Comment by nougator** [comment]
Oh nvm wrong branch

**Pull request merged**
