### PR TITLE
README.md: Fixed RU emoji, added Turkish translation

### PR DESCRIPTION
**Pull request by unickorn**
## Summary

This PR adds a Turkish README and fixes the Russian flag on all READMEs.

## Checklist

- [ ] If code changes were made then they have been tested.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

----

Bonus: Could you also consider adding the hacktoberfest topic to the repo before merging this in? It's a really nice way to get more attention and contribution in October :)

More info here: https://hacktoberfest.digitalocean.com

### CODE REVIEW

**Comment by unickorn** [comment]
If you don't want to add the hacktoberfest topic, it would be really nice if you marked this pull request with a **hacktoberfest-accepted** label :)

**Comment by NhanAZ** [comment]
I think you should close this pr. Link formats have changed

**Comment by unickorn** [comment]
Why? I've also updated them in the PR.

**Comment by NhanAZ** [comment]
Sorry. Maybe I'm a little confused

**Comment by plun1331** [comment]
thats a lot of merge conflicts

**Review by HunterAzar — COMMENTED** [review]
Wut

**Pull request closed without merging**
