### PR TITLE
Added "start.cmd" and "start.bs"

### PR DESCRIPTION
**Pull request by ElectroGamesDev**

### CODE REVIEW

**Comment by Zekiah-A** [comment]
What is .bs?

**Comment by ElectroGamesDev** [comment]
> What is .bs?

It is a bash file. It can be run on both Linux and Mac

**Comment by Zekiah-A** [comment]
Why not just .sh lol?

**Comment by ElectroGamesDev** [comment]
I was going to do .sh.... Im not sure why I did .bs lmao

**Comment by Zekiah-A** [comment]
Maybe it should be changed, as some may not even know what .bs is

**Comment by Zekiah-A** [comment]
~~like me until a few minutes ago~~

**Comment by ElectroGamesDev** [comment]
I will if this pull gets accepted..

**Comment by Zekiah-A** [comment]
https://youtu.be/NGZoX8l-QmA

**Pull request closed without merging**
